### PR TITLE
Port to MOI

### PR DESCRIPTION
**Pull request by joehuchette**
Still preliminary, since I don't have a BARON license on the machine this was written on :)

@tkoolen

### CODE REVIEW

**Comment by tkoolen** [comment]
Thank you very much! I'll try this out.

**Comment by joehuchette** [comment]
Be prepared for it to break almost immediately, I can only verify that “using BARON” doesn’t crash. I’ll pick this up next week when I’m back to my computer with the license.

**Comment by tkoolen** [comment]
OK. Yeah, there are some missing methods and things that need to change. I'm trying to get it to at least solve a very simple problem, but it'll take some effort to get to a full-featured version.

**Comment by tkoolen** [comment]
See #28.

**Comment by tkoolen** [comment]
FYI: the SCIP wrapper seems to be in pretty good shape at this point; could be a good idea to use it as a checklist of functionality to implement, if nothing else.

**Comment by tkoolen** [comment]
Just for my planning, do you still intend to work on this wrapper within the next month or so?

**Comment by joehuchette** [comment]
It’s still on my radar, but realistically I won’t get to this until July.

**Comment by tkoolen** [comment]
Alright, since this is a bit more urgent for me, mind if I take a stab?

**Comment by joehuchette** [comment]
Go for it, I will be back at my computer and able to review in ~10 days.

**Pull request merged**
